export const boxData = [
  {
    title: "BOX DÉCOUVERTE",
    subtitle: "Une aventure en duo",
    imageSrc: "/images/asset4.jpeg",
    imageAlt: "couple",
    link: "/lien-vers-la-box",
  },
  {
    title: "BOX SENSUEL",
    subtitle: "Une aventure sensuelle en duo",
    imageSrc: "/images/asset6.jpeg",
    imageAlt: "bisou dans le cou",
    link: "/lien-vers-la-box",
  },
  {
    title: "ALL INCLUSIVE",
    subtitle: "Une aventure personalisée en duo",
    imageSrc: "/images/asset6.jpeg",
    imageAlt: "bouton de manche",
    link: "/lien-vers-la-box",
  },
  {
    title: "BOX DÉCOUVERTE",
    subtitle: "Une aventure en duo",
    imageSrc: "/images/asset4.jpeg",
    imageAlt: "couple",
    link: "/lien-vers-la-box",
  },
  {
    title: "BOX SENSUEL",
    subtitle: "Une aventure sensuelle en duo",
    imageSrc: "/images/asset6.jpeg",
    imageAlt: "bisou dans le cou",
    link: "/lien-vers-la-box",
  },
  {
    title: "ALL INCLUSIVE",
    subtitle: "Une aventure personalisée en duo",
    imageSrc: "/images/asset6.jpeg",
    imageAlt: "bouton de manche",
    link: "/lien-vers-la-box",
  },
  {
    title: "BOX DÉCOUVERTE",
    subtitle: "Une aventure en duo",
    imageSrc: "/images/asset4.jpeg",
    imageAlt: "couple",
    link: "/lien-vers-la-box",
  },
  {
    title: "BOX SENSUEL",
    subtitle: "Une aventure sensuelle en duo",
    imageSrc: "/images/asset6.jpeg",
    imageAlt: "bisou dans le cou",
    link: "/lien-vers-la-box",
  },
  {
    title: "ALL INCLUSIVE",
    subtitle: "Une aventure personalisée en duo",
    imageSrc: "/images/asset6.jpeg",
    imageAlt: "bouton de manche",
    link: "/lien-vers-la-box",
  },
  {
    title: "BOX DÉCOUVERTE",
    subtitle: "Une aventure en duo",
    imageSrc: "/images/asset4.jpeg",
    imageAlt: "couple",
    link: "/lien-vers-la-box",
  },
  {
    title: "BOX SENSUEL",
    subtitle: "Une aventure sensuelle en duo",
    imageSrc: "/images/asset6.jpeg",
    imageAlt: "bisou dans le cou",
    link: "/lien-vers-la-box",
  },
  {
    title: "ALL INCLUSIVE",
    subtitle: "Une aventure personalisée en duo",
    imageSrc: "/images/asset6.jpeg",
    imageAlt: "bouton de manche",
    link: "/lien-vers-la-box",
  },
];
